# 公式かつ、slim imageかつ、安定バージョンかつ、debian
FROM node:20.2.0-bullseye-slim

ENV TZ Asia/Tokyo

# ARG USERNAME=kaito
# ARG GROUPNAME=kaito
# ARG UID=1000
# ARG GID=1000

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    vim git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# RUN groupadd -g $GID $GROUPNAME && \
#   useradd -m -s /bin/bash -u $UID -g $GID $USERNAME

RUN npm i -g pnpm

USER node
WORKDIR /home/node/react-front